---
swarm_nfs_role: client  # primary, replica, or client
swarm_nfs_primary: "{{ nfs_primary_ip }}"     # Set in inventory
swarm_nfs_replica: "{{ nfs_replica_ip }}"     # Set in inventory
swarm_mount_point: /opt/swarm
swarm_replica_path: /opt/swarm-replica
swarm_replica_sync_interval: "* * * * *"  # every minute
lan_subnet: "{{ lan_cidr }}"                  # Set in inventory
